## Class Imbalance Problem( Regular Loss vs Weighted Loss)

One of the main challange of datasets for medical diagnosis is the impact of `Class Imbalance` on the loss function. Since in the real world dataset there are more healtly(positive) examples than the negative ones, the model is biased to emphasize positive examples while training.

### Regular Loss

$$
L(X, y) =
\begin{cases}
    -\log P(Y = 1| X) \quad \text{if } y = 1\\
    -\log P(Y = 0| X) \quad \text{if } y = 0
\end{cases}
$$

### Weighted Loss

One way to mitigate this impact is to use loss function to weight the losses differently for different classes.

$$
L(X, y) =
\begin{cases}
    w_p \times -\log P(Y = 1| X) \quad \text{if } y = 1\\
    w_n \times -\log P(Y = 0| X) \quad \text{if } y = 0
\end{cases}
$$


Where, weight the loss for $w_p$ and $w_n$ are calculated respectively as:

$$
w_p = \frac {negativeEg}{totalEg} \quad \& \quad w_n = \frac{PositiveEg}{totalEg}
$$

**Let :** $loss_{pos}$ and $loss_{neg}$ refer to the loss with positive examples($y_{true} =1$) and negative examples($y_{true} =0$) respectively.
**Then :** Loss for $i^{th}$ example:

$$
\boxed{loss^{(i)} = loss_{pos}^{(i)} + los_{neg}^{(i)}}
$$

Where,

$$
\boxed{
    loss_{pos}^{(i)} = -1 \times weight_{pos}^{(i)} \times y^{(i)} \times log(\hat{y}^{(i)}) \\
    loss_{neg}^{(i)} = -1 \times weight_{neg}^{(i)} \times (1- y^{(i)}) \times log(1 - \hat{y}^{(i)})
}
$$



In [2]:
import numpy as np

#--------------------------------------------------------------
# Regular Vs Weighted Loss Dummy Binary Classification
#--------------------------------------------------------------

# Imbalanced class (3/4th label = 1)
y_true = np.array([[1],[1],[1],[0]]) 

# Model 1 (Prediction : 0.9 for every examples)
y_pred_1 = 0.9*np.ones(y_true.shape)

# Model 2 (Prediction : 0.1 for every examples)
y_pred_2 = 0.1*np.ones(y_true.shape)

#--------------------------------------------------------------
# Regular Loss Model 1 & 2
loss_1 = -1 * np.sum(y_true * np.log(y_pred_1)) + \
         -1 * np.sum((1 - y_true) * np.log(1-y_pred_1))

loss_2 = -1 * np.sum(y_true * np.log(y_pred_2)) + \
         -1 * np.sum((1-y_true) * np.log(1-y_pred_2))

#--------------------------------------------------------------
# Weighted Loss Model 1 & 2
w_p = 1/4
w_n = 3/4

# Loss Model 1
loss_pos_1 = -1 * np.sum(w_p * y_true * np.log(y_pred_1))
loss_neg_1 = -1 * np.sum(w_n * (1-y_true) * np.log(1-y_pred_1))
loss_wtd_1 = loss_pos_1 + loss_neg_1

# Loss Model 2
loss_pos_2 = -1 * np.sum(w_p * y_true * np.log(y_pred_2))
loss_neg_2 = -1 * np.sum(w_n * (1-y_true) * np.log(1-y_pred_2))
loss_wtd_2 = loss_pos_2 + loss_neg_2

#--------------------------------------------------------------
# Summary Regular and Weighted Loss
#--------------------------------------------------------------

summary = f"""
---------------------------------------------------------------
\t\tDummy Models with Regular Loss
---------------------------------------------------------------
\nDataset Labels (Imbalanced) : \n{y_true} 
\nModel 1 has prediction 0.9 for all examples
{y_pred_1}
\nModel 2 has prediction 0.1 for all examples
{y_pred_2:}

Regular Loss Model 1: {loss_1}
Regular Loss Model 2: {loss_2:}

Since this dummy dataset label has Class Imbalance (3/4 of labels are '1'),
the regular loss function implies that Model-1(with high prediction 0.9) is 
better than Model-2( with low prediction 0.1). Hence, Bigger loss for Model-2
with prediction closer to 0.

---------------------------------------------------------------
\t\tDummy Models with Weighted Loss
---------------------------------------------------------------

Weighted Loss Model 1: {loss_wtd_1:.4f}
Weighted Loss Model 2: {loss_wtd_2:.4f}

Loss 1 positive: {loss_pos_1:.4f} \t Loss 1 negative: {loss_neg_1:.4f}
Loss 2 positive: {loss_pos_2:.4f} \t Loss 2 negative: {loss_neg_2:.4f}

Inspite of imbalanced class( 1 - negative & 3 - positive examples), the 
weighted loss has same performance. the weighted loss accounts this by 
giving more weight to the negative label than to the positive ones.
"""

print(summary)


---------------------------------------------------------------
		Dummy Models with Regular Loss
---------------------------------------------------------------

Dataset Labels (Imbalanced) : 
[[1]
 [1]
 [1]
 [0]] 

Model 1 has prediction 0.9 for all examples
[[0.9]
 [0.9]
 [0.9]
 [0.9]]

Model 2 has prediction 0.1 for all examples
[[0.1]
 [0.1]
 [0.1]
 [0.1]]

Regular Loss Model 1: 2.618666639967525
Regular Loss Model 2: 7.013115794639963

Since this dummy dataset label has Class Imbalance (3/4 of labels are '1'),
the regular loss function implies that Model-1(with high prediction 0.9) is 
better than Model-2( with low prediction 0.1). Hence, Bigger loss for Model-2
with prediction closer to 0.

---------------------------------------------------------------
		Dummy Models with Weighted Loss
---------------------------------------------------------------

Weighted Loss Model 1: 1.8060
Weighted Loss Model 2: 1.8060

Loss 1 positive: 0.0790 	 Loss 1 negative: 1.7269
Loss 2 positive: 1.

In [3]:
#--------------------------------------------------------------
# Weighted Loss Dummy Multi-class Classification
#--------------------------------------------------------------

# E.g. Dataset with Two Classes (Disease)
y_true = np.array(
    [[1,0]
    ,[1,0]
    ,[1,0]
    ,[1,0]
    ,[0,1]] 
)

# Axis ( 0 | 1)
# print(f'Sum Axis = 0 : {np.sum(y_true, axis=0)}')
# print(f'Sum Axis = 1 : {np.sum(y_true, axis=1)}')

# calculate the weights
w_p = np.sum(y_true == 0, axis=0)/ y_true.shape[0]
w_n = np.sum(y_true == 1, axis=0)/ y_true.shape[0]

# Models
y_pred = np.ones(y_true.shape)
y_pred[:,0] = 0.3 * y_pred[:,0]
y_pred[:,1] = 0.7 * y_pred[:,1]

# Loss Model 1
loss_pos_0 = -1 * np.sum(w_p[0] * y_true[:,0] * np.log(y_pred[:,0]))
loss_neg_0 = -1 * np.sum(w_n[0] * (1-y_true[:,0]) * np.log(1-y_pred[:,0]))
loss_0 = loss_pos_0 + loss_neg_0

# Loss Model 2
loss_pos_1 = -1 * np.sum(w_p[1] * y_true[:,1] * np.log(y_pred[:,1]))
loss_neg_1 = -1 * np.sum(w_n[1] * (1-y_true[:,1]) * np.log(1-y_pred[:,1]))
loss_1 = loss_pos_1 + loss_neg_1

#--------------------------------------------------------------
# Summary Weighted Loss 
#--------------------------------------------------------------
summary = f"""
---------------------------------------------------------------
\tSummary Weighted Loss Multi-Class Problems
---------------------------------------------------------------
\nDataset Labels (Imbalanced)[C0 C1] : \n{y_true}
\nModel that always predicts same value[M1 M2] : \n{y_pred}

\nColumn0( Disease 1 )
M1 y_pred:{y_pred[:,0]}
y_true[:,0]:{y_true[:,0]}

\nColumn1( Disease 2 )
M2 y_pred:{y_pred[:,1]}
y_true[:,1]:{y_true[:,1]}

w_p[0]: {w_p[0]} \t\t w_n[0]:{w_n[0]}
w_p[1]: {w_p[1]} \t\t w_n[1]:{w_n[1]}

Loss C0 positive: {loss_pos_0:.4f} \t Loss C0 negative: {loss_neg_0:.4f}
Loss C1 positive: {loss_pos_1:.4f} \t Loss C1 negative: {loss_neg_1:.4f}

Weighted Loss C0: {loss_0:.4f}
Weighted Loss C1: {loss_1:.4f}

---------------------------------------------------------------
"""

print(summary)


---------------------------------------------------------------
	Summary Weighted Loss Multi-Class Problems
---------------------------------------------------------------

Dataset Labels (Imbalanced)[C0 C1] : 
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]

Model that always predicts same value[M1 M2] : 
[[0.3 0.7]
 [0.3 0.7]
 [0.3 0.7]
 [0.3 0.7]
 [0.3 0.7]]


Column0( Disease 1 )
M1 y_pred:[0.3 0.3 0.3 0.3 0.3]
y_true[:,0]:[1 1 1 1 0]


Column1( Disease 2 )
M2 y_pred:[0.7 0.7 0.7 0.7 0.7]
y_true[:,1]:[0 0 0 0 1]

w_p[0]: 0.2 		 w_n[0]:0.8
w_p[1]: 0.8 		 w_n[1]:0.2

Loss C0 positive: 0.9632 	 Loss C0 negative: 0.2853
Loss C1 positive: 0.2853 	 Loss C1 negative: 0.9632

Weighted Loss C0: 1.2485
Weighted Loss C1: 1.2485

---------------------------------------------------------------

